version: "3.8"

services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: barbershop_test_runner
    env_file:
      - .env
    environment:
      REDIS_URL: redis://barbershop_redis_test:6379/0
      TEST_DATABASE_URL: sqlite+aiosqlite:///:memory
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    networks:
      - backend_test

networks:
  backend_test:
